{{- if .Values.sapi.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sapi
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: sapi
spec:
  replicas: {{ .Values.sapi.replicaCount }}
  selector:
    matchLabels:
      {{- include "widgetario.selectorLabels" . | nindent 6 }}
      app: sapi
  template:
    metadata:
      labels:
        {{- include "widgetario.selectorLabels" . | nindent 8 }}
        app: sapi
    spec:
      containers:
        - name: sapi
          image: "{{ .Values.sapi.image.repository }}:{{ .Values.sapi.image.tag }}"
          imagePullPolicy: {{ .Values.sapi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if .Values.global.includeReadiness }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          {{- if .Values.global.includeLiveness }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- end }}
          {{- if .Values.global.includeResources }}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          {{- end }}
{{- end }}
