{{- if .Values.papi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-papi
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: papi
spec:
  type: {{ .Values.papi.service.type }}
  ports:
    - port: {{ .Values.papi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "widgetario.selectorLabels" . | nindent 4 }}
    app: papi
---
{{- end }}
{{- if .Values.sapi.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sapi
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: sapi
spec:
  type: {{ .Values.sapi.service.type }}
  ports:
    - port: {{ .Values.sapi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "widgetario.selectorLabels" . | nindent 4 }}
    app: sapi
---
{{- end }}
{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: web
spec:
  type: {{ .Values.web.service.type }}
  ports:
    - port: {{ .Values.web.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "widgetario.selectorLabels" . | nindent 4 }}
    app: web
---
{{- end }}
{{- if .Values.pdb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pdb
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: pdb
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "widgetario.selectorLabels" . | nindent 4 }}
    app: pdb
{{- end }}
