{{- if .Values.web.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    {{- include "widgetario.labels" . | nindent 4 }}
    app: web
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      {{- include "widgetario.selectorLabels" . | nindent 6 }}
      app: web
  template:
    metadata:
      labels:
        {{- include "widgetario.selectorLabels" . | nindent 8 }}
        app: web
    spec:
      initContainers:
        - name: init-theme
          image: {{ .Values.web.loggerImage }}
          command: ['sh', '-c', 'echo "Theme: {{ .Values.web.theme }}" > /tmp/theme.txt']
          volumeMounts:
            - name: theme
              mountPath: /tmp
      containers:
        - name: web
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: theme
              mountPath: /app/theme
          {{- if .Values.global.includeReadiness }}
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          {{- end }}
          {{- if .Values.global.includeLiveness }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          {{- end }}
          env:
            - name: PRODUCTS_API_URL
              value: "http://{{ .Release.Name }}-papi"
            - name: STOCK_API_URL
              value: "http://{{ .Release.Name }}-sapi"
            - name: Widgetario__Theme
              value: {{ .Values.web.theme }}
          {{- if .Values.global.includeResources }}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          {{- end }}
      volumes:
        - name: theme
          emptyDir: {}
{{- end }}
